### ISSUE TITLE
contribution field in spreadsheet is multivalued, but not handled that way

### ISSUE THREAD

**Issue by eads** [nprapps/graeae#123]

**Comment by livlab** [comment]
Wouldn't it be more useful going forward if the data capture was categorized rather than open fields? Seems really consistent so Emily and Ariel could just check off the activity they performed from a list:
- source existing image (from wires, etc)
- source new original image (from wires, etc)
- Viz shoot 
- tone/edit photo
- edit video
- coach (intern, journalist, etc)
- commission (photographer, illustrator, etc)
- curate slideshow
- multimedia page buildout
- troubleshoot photo/video issue with journalist, etc)
- make screenshots, crops

this is based on all the data so far. Seems like a pretty narrow set. (if better worded it might make capture easier for them and contribution field easier to parse).

**Comment by eads** [comment]
That's what they do, it's just multi-valued.

On Thu, Jun 4, 2015 at 10:23 AM, Livia Labate notifications@github.com
wrote:

> Wouldn't it be more useful going forward if the data capture was
> categorized rather than open fields? Seems really consistent so Emily and
> Ariel could just check off the activity they performed from a list:
> - source existing image (from wires, etc)
> - source new original image (from wires, etc)
> - Viz shoot
> - tone/edit photo
> - edit video
> - coach (intern, journalist, etc)
> - commission (photographer, illustrator, etc)
> - curate slideshow
> - multimedia page buildout
> - troubleshoot photo/video issue with journalist, etc)
> - make screenshots, crops
> 
> this is based on all the data so far. Seems like a pretty narrow set. (if
> better worded it might make capture easier for them and contribution field
> easier to parse).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nprapps/graeae/issues/123#issuecomment-108913023.

## 

David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by livlab** [comment]
Leaving as is. CSV work.
