### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by livlab** [nprapps/graeae#170]
(possibly stupid question) 

Given the issue we came across the other day with journalism (#163), isn't it helpful to have utf-8 encoding noted at the top of all python files? 

``` python
# -*- coding: utf-8 -*-
```

https://www.python.org/dev/peps/pep-0263/

I see this in tutorials but am not sure how external libraries like journalism respond to something stated in the python file about itself.

**Comment by eads** [comment]
That's not a stupid question at all!

This covers all the letters in your code itself (e.g. defining a variable
like `jalapeño = 'chile'`) and string definitions (e.g. you can write
`chile = 'jalapeño'` instead of `chile = u'jalapeño'`). It also covers user
input that your program might solicit. This is how Tarbell allows unicode
characters when asking the user what they'd like to name their project.

But there's two huge caveats:
- External data sources (e.g. stuff that's coming from an API or a file)
  retain their original encoding
- Code paths that assume an encoding and try to encode/decode based on that
  assumption. So if you call a library that assumes a string was not unicode
  and needs to be encoded, you still run into errors.

Because of the nature of our work and the chaos of unicode in Python, we
run into both those caveats a lot and we still have to code around it.
Yech.

**Comment by livlab** [comment]
Thank you for explaining this!
